import type {
  AppNotification,
  Challenge,
  Community,
  DiscoverItem,
  Post,
  ProgressSnapshot,
  Session,
  Trainer,
  User,
  Workout,
} from "@/lib/types";

// ============================================================
// Seed data.
//
// Every name, place, spot-count and figure is taken from the PRD's
// own worked examples so the prototype reads as a Lagos product
// rather than lorem ipsum. Where the PRD gives a number, it is
// preserved exactly (47/100 spots, 12 training today, 45→55kg).
//
// This is fictional. No real people, addresses or phone numbers.
// ============================================================

export const CURRENT_USER_ID = "david";

export const USERS: User[] = [
  {
    id: "david",
    name: "David",
    initials: "DA",
    tone: 0,
    age: 27,
    area: "lekki",
    fitnessLevel: "intermediate",
    goals: ["muscle-gain", "strength"],
    activities: ["gym", "running"],
    preferredDays: ["mon", "tue", "thu", "sat"],
    preferredSlots: ["evening"],
    currentGym: "i-Fitness Lekki",
    verified: true,
    handle: "@david.a",
    bio: "Intermediate. Push/pull/legs. Trying to make 6AM a habit.",
  },
  {
    id: "ngozi",
    name: "Ngozi Eze",
    initials: "NE",
    tone: 1,
    age: 29,
    area: "victoria-island",
    fitnessLevel: "advanced",
    goals: ["strength", "sports-performance"],
    activities: ["gym"],
    preferredDays: ["mon", "wed", "fri"],
    preferredSlots: ["dawn", "morning"],
    verified: true,
    handle: "@ngozi.lifts",
    bio: "Powerlifting. Squat rack is my office.",
  },
  {
    id: "tunde",
    name: "Tunde Bakare",
    initials: "TB",
    tone: 2,
    age: 31,
    area: "lekki",
    fitnessLevel: "intermediate",
    goals: ["endurance", "running"],
    activities: ["running", "cycling"],
    preferredDays: ["tue", "thu", "sat", "sun"],
    preferredSlots: ["dawn"],
    verified: true,
    handle: "@tunde.runs",
    bio: "5AM crew. Lagos traffic is my warm-up.",
  },
  {
    id: "chidinma",
    name: "Chidinma Okafor",
    initials: "CO",
    tone: 3,
    age: 25,
    area: "yaba",
    fitnessLevel: "beginner",
    goals: ["general-fitness", "healthy-lifestyle"],
    activities: ["running", "yoga"],
    preferredDays: ["wed", "sat"],
    preferredSlots: ["evening"],
    verified: false,
    handle: "@chidinma.o",
    bio: "Year one. Still learning the names of the machines.",
  },
  {
    id: "emeka",
    name: "Emeka Nwosu",
    initials: "EN",
    tone: 4,
    age: 34,
    area: "ikeja",
    fitnessLevel: "advanced",
    goals: ["muscle-gain", "strength"],
    activities: ["gym", "football"],
    preferredDays: ["mon", "tue", "thu", "fri"],
    preferredSlots: ["evening", "night"],
    verified: true,
    handle: "@emeka.n",
    bio: "Twelve years lifting. Still chasing a 140 bench.",
  },
  {
    id: "bola",
    name: "Bola Adeyemi",
    initials: "BA",
    tone: 5,
    age: 28,
    area: "victoria-island",
    fitnessLevel: "intermediate",
    goals: ["weight-loss", "general-fitness"],
    activities: ["running", "pilates"],
    preferredDays: ["mon", "wed", "fri"],
    preferredSlots: ["morning"],
    verified: true,
    handle: "@bola.moves",
    bio: "Half marathon in training. Kicks off at VI.",
  },
  {
    id: "kelechi",
    name: "Kelechi Obi",
    initials: "KO",
    tone: 6,
    age: 26,
    area: "ikoyi",
    fitnessLevel: "intermediate",
    goals: ["sports-performance", "endurance"],
    activities: ["football", "basketball"],
    preferredDays: ["tue", "thu", "sat"],
    preferredSlots: ["afternoon", "evening"],
    verified: false,
    handle: "@kelechi.obi",
    bio: "Five-a-side every Friday. Never miss.",
  },
  {
    id: "funke",
    name: "Funke Balogun",
    initials: "FB",
    tone: 7,
    age: 33,
    area: "surulere",
    fitnessLevel: "beginner",
    goals: ["flexibility", "healthy-lifestyle"],
    activities: ["yoga", "home-workouts"],
    preferredDays: ["mon", "thu", "sun"],
    preferredSlots: ["morning", "afternoon"],
    verified: false,
    handle: "@funke.b",
    bio: "Mobility over momentum.",
  },
  {
    id: "segun",
    name: "Segun Adebayo",
    initials: "SA",
    tone: 1,
    age: 30,
    area: "lekki",
    fitnessLevel: "advanced",
    goals: ["endurance", "running"],
    activities: ["running"],
    preferredDays: ["mon", "wed", "fri", "sun"],
    preferredSlots: ["dawn"],
    verified: true,
    handle: "@segun.pace",
    bio: "Sub-25 5K. Chasing sub-24.",
  },
  {
    id: "amaka",
    name: "Amaka Uche",
    initials: "AU",
    tone: 2,
    age: 27,
    area: "yaba",
    fitnessLevel: "intermediate",
    goals: ["general-fitness", "weight-loss"],
    activities: ["gym", "yoga"],
    preferredDays: ["tue", "thu", "sat"],
    preferredSlots: ["evening"],
    verified: true,
    handle: "@amaka.u",
    bio: "Small wins, every week.",
  },
  {
    id: "zainab",
    name: "Zainab Ibrahim",
    initials: "ZI",
    tone: 3,
    age: 24,
    area: "ikeja",
    fitnessLevel: "beginner",
    goals: ["weight-loss", "general-fitness"],
    activities: ["running", "gym"],
    preferredDays: ["mon", "wed", "fri"],
    preferredSlots: ["evening"],
    verified: false,
    handle: "@zainab.i",
    bio: "Here for the community, staying for the streaks.",
  },
  {
    id: "tobi",
    name: "Tobi Alabi",
    initials: "TA",
    tone: 4,
    age: 32,
    area: "ikoyi",
    fitnessLevel: "advanced",
    goals: ["strength", "muscle-gain"],
    activities: ["gym"],
    preferredDays: ["mon", "tue", "thu", "fri"],
    preferredSlots: ["morning", "evening"],
    verified: true,
    handle: "@tobi.alabi",
    bio: "Old school splits. New school recovery.",
  },
];

export const ME: User = USERS[0];

// ---------- Communities (PRD §9) ----------

export const COMMUNITIES: Community[] = [
  {
    id: "lekki-strength-crew",
    name: "Lekki Strength Crew",
    emoji: "🏋️",
    area: "lekki",
    activity: "gym",
    goal: "strength",
    level: "intermediate",
    cadence: "3× per week",
    members: 1284,
    featuredMemberIds: ["ngozi", "tobi", "david", "emeka", "segun"],
    tagline: "Barbells, chalk and 6AM accountability.",
    description:
      "A Lekki-based lifting community for people training with intent. Open sessions Monday, Wednesday and Saturday at i-Fitness. Beginners welcome — we pair you with a spotter in your first week.",
    adminNames: ["Ngozi Eze", "Tobi Alabi"],
    todayTraining: 12,
    badge: "Fastest growing",
    nextSessionId: "bench-squat-night",
    joined: true,
    schedule: [
      { day: "mon", time: "6:00 PM", activity: "Strength" },
      { day: "wed", time: "6:00 PM", activity: "Upper body" },
      { day: "sat", time: "7:30 AM", activity: "Open gym" },
    ],
  },
  {
    id: "lagos-runners",
    name: "Lagos Runners",
    emoji: "🏃",
    area: "victoria-island",
    activity: "running",
    goal: "endurance",
    level: "intermediate",
    cadence: "4× per week",
    members: 3420,
    featuredMemberIds: ["segun", "tunde", "bola", "chidinma"],
    tagline: "The fastest-growing run crew on the mainland and island.",
    description:
      "Five running routes across Lagos, a WhatsApp-free calendar, and pace groups from 4:30 to 7:30 per km. We train for the Lagos Marathon every January.",
    adminNames: ["Segun Adebayo", "Tunde Bakare"],
    todayTraining: 34,
    badge: "Verified organiser",
    nextSessionId: "sat-5km",
    joined: true,
    schedule: [
      { day: "tue", time: "6:00 AM", activity: "Easy 5K" },
      { day: "thu", time: "6:00 AM", activity: "Intervals" },
      { day: "sat", time: "6:00 AM", activity: "Long run" },
      { day: "sun", time: "7:00 AM", activity: "Recovery" },
    ],
  },
  {
    id: "vi-women-who-run",
    name: "Victoria Island Women Who Run",
    emoji: "👟",
    area: "victoria-island",
    activity: "running",
    goal: "general-fitness",
    level: "beginner",
    cadence: "3× per week",
    members: 862,
    featuredMemberIds: ["bola", "zainab", "funke"],
    tagline: "No pace too slow. No question too basic.",
    description:
      "A beginner-first women's run community. Every session starts with a walk-run plan for people who have never run before. Route is always lit and always staffed with a sweeper.",
    adminNames: ["Bola Adeyemi"],
    todayTraining: 9,
    nextSessionId: "vw-r10k",
    joined: false,
    schedule: [
      { day: "wed", time: "6:30 PM", activity: "Walk-run" },
      { day: "sat", time: "7:00 AM", activity: "Easy 5K" },
      { day: "sun", time: "7:30 AM", activity: "Long run" },
    ],
  },
  {
    id: "lagos-cycling-community",
    name: "Lagos Cycling Community",
    emoji: "🚴",
    area: "lekki",
    activity: "cycling",
    goal: "endurance",
    level: "intermediate",
    cadence: "2× per week",
    members: 1105,
    featuredMemberIds: ["tunde", "kelechi"],
    tagline: "Sunrise loops before the bridges close.",
    description:
      "Weekend distance rides out of Ikoyi and Lekki. Road and gravel welcome. Helmet mandatory, no-drop policy.",
    adminNames: ["Tunde Bakare"],
    todayTraining: 0,
    joined: false,
    schedule: [
      { day: "sat", time: "6:30 AM", activity: "60km loop" },
      { day: "sun", time: "6:30 AM", activity: "Recovery spin" },
    ],
  },
  {
    id: "ikeja-beginners-fitness",
    name: "Ikeja Beginners Fitness",
    emoji: "🌟",
    area: "ikeja",
    activity: "gym",
    goal: "general-fitness",
    level: "beginner",
    cadence: "3× per week",
    members: 743,
    featuredMemberIds: ["zainab", "chidinma"],
    tagline: "Starting over is a valid starting point.",
    description:
      "For people who have never trained or are picking it back up. No ego lifting, no unsolicited advice. Every session is coached and every movement is explained.",
    adminNames: ["Zainab Ibrahim"],
    todayTraining: 7,
    badge: "Beginner-friendly",
    joined: false,
    schedule: [
      { day: "mon", time: "6:30 PM", activity: "Full body" },
      { day: "wed", time: "6:30 PM", activity: "Conditioning" },
      { day: "sat", time: "9:00 AM", activity: "Group class" },
    ],
  },
  {
    id: "yaba-run-club",
    name: "Yaba Run Club",
    emoji: "🏃",
    area: "yaba",
    activity: "running",
    goal: "endurance",
    level: "beginner",
    cadence: "2× per week",
    members: 618,
    featuredMemberIds: ["chidinma", "amaka"],
    tagline: "Mainland miles, Friday nights.",
    description:
      "A social run crew for students and young professionals. Route ends at a spot on Herbert Macaulay — the run is the excuse.",
    adminNames: ["Amaka Uche"],
    todayTraining: 0,
    joined: false,
    schedule: [
      { day: "fri", time: "6:00 PM", activity: "Social 5K" },
      { day: "sun", time: "7:00 AM", activity: "Long run" },
    ],
  },
  {
    id: "ikoyi-five-a-side",
    name: "Ikoyi Five-a-Side",
    emoji: "⚽",
    area: "ikoyi",
    activity: "football",
    goal: "sports-performance",
    level: "intermediate",
    cadence: "2× per week",
    members: 497,
    featuredMemberIds: ["kelechi", "emeka"],
    tagline: "Fixtures every Friday and Sunday.",
    description:
      "Organised five-a-side with proper refs and a rotating fixture list. Bibs provided. Pay-per-play, no annual commitment.",
    adminNames: ["Kelechi Obi"],
    todayTraining: 4,
    nextSessionId: "five-a-side",
    joined: false,
    schedule: [
      { day: "fri", time: "7:00 PM", activity: "League fixture" },
      { day: "sun", time: "5:00 PM", activity: "Friendly" },
    ],
  },
  {
    id: "surulere-yoga-circle",
    name: "Surulere Yoga Circle",
    emoji: "🧘",
    area: "surulere",
    activity: "yoga",
    goal: "flexibility",
    level: "beginner",
    cadence: "3× per week",
    members: 312,
    featuredMemberIds: ["funke"],
    tagline: "Breath first. Posture second. Instagram never.",
    description:
      "Morning mobility and slow flow sessions. Mats provided. Designed for people who sit at a desk for nine hours.",
    adminNames: ["Funke Balogun"],
    todayTraining: 5,
    joined: false,
    schedule: [
      { day: "mon", time: "7:00 AM", activity: "Mobility" },
      { day: "thu", time: "7:00 AM", activity: "Slow flow" },
      { day: "sun", time: "8:00 AM", activity: "Restorative" },
    ],
  },
];

// ---------- Sessions & Events (PRD §12) ----------

export const SESSIONS: Session[] = [
  {
    id: "bench-squat-night",
    title: "Bench & Squat Night",
    activity: "gym",
    dayLabel: "Today",
    date: "Wed 29 Oct",
    time: "6:00 PM",
    location: "i-Fitness Lekki",
    area: "lekki",
    level: "intermediate",
    maxSpots: 40,
    spotsTaken: 12,
    cost: 0,
    organizerName: "Ngozi Eze",
    communityId: "lekki-strength-crew",
    description:
      "Heavy triples on bench, working sets on squat. Bring a belt if you have one. Spotters provided on every rack.",
    attendeeIds: ["ngozi", "tobi", "david", "emeka", "amaka", "segun"],
    status: "upcoming",
    joined: true,
    checkedIn: false,
  },
  {
    id: "sat-5km",
    title: "Saturday 5KM Run",
    activity: "running",
    dayLabel: "Saturday",
    date: "Sat 1 Nov",
    time: "6:00 AM",
    location: "Lekki Phase 1",
    area: "lekki",
    level: "intermediate",
    maxSpots: 100,
    spotsTaken: 47,
    cost: 0,
    organizerName: "Segun Adebayo",
    communityId: "lagos-runners",
    description:
      "The classic loop. Three pace groups — 5:00, 6:00 and 7:00 per km. No one finishes alone.",
    attendeeIds: ["segun", "tunde", "bola", "chidinma", "david", "amaka"],
    status: "upcoming",
    joined: true,
    checkedIn: false,
  },
  {
    id: "sunday-yoga-vi",
    title: "Sunday Yoga — VI",
    activity: "yoga",
    dayLabel: "Sunday",
    date: "Sun 2 Nov",
    time: "8:00 AM",
    location: "Eko Atlantic Lawn",
    area: "victoria-island",
    level: "beginner",
    maxSpots: 30,
    spotsTaken: 22,
    cost: 2000,
    organizerName: "Funke Balogun",
    description:
      "Outdoor slow flow to close the week. Mats available to borrow, bring a towel and water.",
    attendeeIds: ["funke", "bola", "zainab", "chidinma"],
    status: "upcoming",
    joined: false,
    checkedIn: false,
  },
  {
    id: "five-a-side",
    title: "Five-a-side — Lekki",
    activity: "football",
    dayLabel: "Friday",
    date: "Fri 31 Oct",
    time: "7:00 PM",
    location: "Lekki Football Pitch 2",
    area: "lekki",
    level: "intermediate",
    maxSpots: 22,
    spotsTaken: 18,
    cost: 1500,
    organizerName: "Kelechi Obi",
    communityId: "ikoyi-five-a-side",
    description:
      "League fixture. Bibs provided, ref confirmed. Pay on arrival by transfer.",
    attendeeIds: ["kelechi", "emeka", "tobi"],
    status: "upcoming",
    joined: false,
    checkedIn: false,
  },
  {
    id: "saturday-cycling",
    title: "Saturday Cycling — Lagos",
    activity: "cycling",
    dayLabel: "Saturday",
    date: "Sat 1 Nov",
    time: "6:30 AM",
    location: "Ikoyi Link Bridge start",
    area: "ikoyi",
    level: "intermediate",
    maxSpots: 25,
    spotsTaken: 14,
    cost: 0,
    organizerName: "Tunde Bakare",
    communityId: "lagos-cycling-community",
    description:
      "60km loop before the bridges shut. Helmet mandatory. Mechanical support follows in the support car.",
    attendeeIds: ["tunde", "kelechi"],
    status: "upcoming",
    joined: false,
    checkedIn: false,
  },
  {
    id: "hiit-45-ikeja",
    title: "HIIT 45 — Ikeja",
    activity: "gym",
    dayLabel: "Thursday",
    date: "Thu 30 Oct",
    time: "6:30 PM",
    location: "Rocks Gym, Opebi",
    area: "ikeja",
    level: "advanced",
    maxSpots: 25,
    spotsTaken: 25,
    cost: 3000,
    organizerName: "Emeka Nwosu",
    description:
      "Forty-five minutes, twelve stations, no rest. Bring your own towel.",
    attendeeIds: ["emeka", "zainab", "amaka", "tobi"],
    status: "upcoming",
    joined: false,
    checkedIn: false,
  },
  {
    id: "vw-r10k",
    title: "Beginners 10K Build — Week 3",
    activity: "running",
    dayLabel: "Wednesday",
    date: "Wed 29 Oct",
    time: "6:30 PM",
    location: "Eko Atlantic Promenade",
    area: "victoria-island",
    level: "beginner",
    maxSpots: 40,
    spotsTaken: 26,
    cost: 0,
    organizerName: "Bola Adeyemi",
    communityId: "vi-women-who-run",
    description:
      "Week three of the walk-run progression. 40 minutes, no one gets dropped.",
    attendeeIds: ["bola", "zainab", "chidinma"],
    status: "upcoming",
    joined: false,
    checkedIn: false,
  },
  {
    id: "lane-swim",
    title: "Lane Swim — VI",
    activity: "swimming",
    dayLabel: "Tuesday",
    date: "Tue 4 Nov",
    time: "7:00 AM",
    location: "Mobolaji Johnson Arena",
    area: "victoria-island",
    level: "intermediate",
    maxSpots: 20,
    spotsTaken: 8,
    cost: 1000,
    organizerName: "Bola Adeyemi",
    description: "Two lanes reserved. Own goggles required.",
    attendeeIds: ["bola", "david"],
    status: "upcoming",
    joined: false,
    checkedIn: false,
  },
];

// ---------- Discover (PRD §11) ----------

export const DISCOVER_ITEMS: DiscoverItem[] = [
  {
    id: "d-i-fitness",
    category: "gyms",
    title: "i-Fitness Lekki",
    emoji: "🏋️",
    area: "lekki",
    distanceKm: 1.2,
    meta: "Open till 10 PM · Day pass ₦4,500",
    rating: 4.6,
    verified: true,
    badge: "Popular near you",
  },
  {
    id: "d-rocks-gym",
    category: "gyms",
    title: "Rocks Gym Ikeja",
    emoji: "🏋️",
    area: "ikeja",
    distanceKm: 9.4,
    meta: "Open till 9 PM · ₦18,000/month",
    rating: 4.4,
    verified: true,
  },
  {
    id: "d-curves-yaba",
    category: "gyms",
    title: "Curves Yaba",
    emoji: "🏋️",
    area: "yaba",
    distanceKm: 6.8,
    meta: "Open till 8 PM · Women only",
    rating: 4.7,
    verified: false,
  },
  {
    id: "d-lekki-run-club",
    category: "run-clubs",
    title: "Lekki Run Club",
    emoji: "🏃",
    area: "lekki",
    distanceKm: 0.9,
    meta: "Tue & Thu · 6:00 AM · Free",
    rating: 4.8,
    verified: true,
    badge: "12 members joined this week",
    href: "/app/community",
  },
  {
    id: "d-yaba-run-club",
    category: "run-clubs",
    title: "Yaba Run Club",
    emoji: "🏃",
    area: "yaba",
    distanceKm: 7.2,
    meta: "Fri · 6:00 PM · Free",
    rating: 4.5,
    verified: true,
    href: "/app/community",
  },
  {
    id: "d-sunday-yoga",
    category: "classes",
    title: "Sunday Yoga — VI",
    emoji: "🧘",
    area: "victoria-island",
    distanceKm: 4.1,
    meta: "Sun · 8:00 AM · ₦2,000",
    rating: 4.9,
    verified: true,
    href: "/app/sessions",
  },
  {
    id: "d-hiit-45",
    category: "classes",
    title: "HIIT 45 — Ikeja",
    emoji: "🔥",
    area: "ikeja",
    distanceKm: 10.2,
    meta: "Thu · 6:30 PM · ₦3,000",
    rating: 4.6,
    verified: true,
    badge: "Full this week",
    href: "/app/sessions",
  },
  {
    id: "d-pilates-vi",
    category: "classes",
    title: "Pilates Room VI",
    emoji: "🤸",
    area: "victoria-island",
    distanceKm: 3.8,
    meta: "Daily · From 7:00 AM · ₦4,000",
    rating: 4.7,
    verified: false,
  },
  {
    id: "d-five-a-side",
    category: "sports",
    title: "Five-a-side — Lekki",
    emoji: "⚽",
    area: "lekki",
    distanceKm: 2.4,
    meta: "Fri · 7:00 PM · ₦1,500",
    rating: 4.5,
    verified: true,
    href: "/app/sessions",
  },
  {
    id: "d-ikoyi-hoops",
    category: "sports",
    title: "Ikoyi Basketball Nights",
    emoji: "🏀",
    area: "ikoyi",
    distanceKm: 5.6,
    meta: "Mon & Wed · 7:30 PM · Free",
    rating: 4.3,
    verified: false,
  },
  {
    id: "d-tennis-ajah",
    category: "sports",
    title: "Ajah Tennis Courts",
    emoji: "🎾",
    area: "lekki",
    distanceKm: 12.1,
    meta: "Open daily · Court hire ₦3,000",
    rating: 4.1,
    verified: false,
  },
  {
    id: "d-vw-10k",
    category: "events",
    title: "Women Who Run 10K",
    emoji: "📅",
    area: "victoria-island",
    distanceKm: 4.4,
    meta: "Sat 15 Nov · ₦5,000 · 240 spots",
    rating: 4.9,
    verified: true,
    badge: "Selling fast",
  },
  {
    id: "d-marathon-warmup",
    category: "events",
    title: "Lagos Marathon Warm-Up",
    emoji: "📅",
    area: "victoria-island",
    distanceKm: 4.9,
    meta: "Sun 9 Nov · Free · 500 spots",
    rating: 4.8,
    verified: true,
  },
  {
    id: "d-padelpalooza",
    category: "events",
    title: "Padelpalooza Lagos",
    emoji: "📅",
    area: "lekki",
    distanceKm: 3.1,
    meta: "Sat 8 Nov · ₦12,000 · 64 spots",
    rating: 4.6,
    verified: false,
  },
  {
    id: "d-comm-lekki-strength",
    category: "communities",
    title: "Lekki Strength Crew",
    emoji: "🏋️",
    area: "lekki",
    distanceKm: 1.2,
    meta: "1,284 members · 3× per week",
    verified: true,
    badge: "Fastest growing",
    href: "/app/community/lekki-strength-crew",
  },
  {
    id: "d-comm-lagos-runners",
    category: "communities",
    title: "Lagos Runners",
    emoji: "🏃",
    area: "victoria-island",
    distanceKm: 4.1,
    meta: "3,420 members · 4× per week",
    verified: true,
    badge: "Verified organiser",
    href: "/app/community",
  },
  {
    id: "d-comm-ikeja-beginners",
    category: "communities",
    title: "Ikeja Beginners Fitness",
    emoji: "🌟",
    area: "ikeja",
    distanceKm: 9.8,
    meta: "743 members · 3× per week",
    badge: "Beginner-friendly",
    href: "/app/community",
  },
  {
    id: "d-ch-gym-30",
    category: "challenges",
    title: "30-Day Gym Challenge",
    emoji: "🏋️",
    area: "lekki",
    distanceKm: 0,
    meta: "Goal: 20 workouts · 11 days left",
    verified: true,
    href: "/app/progress",
  },
  {
    id: "d-ch-50km",
    category: "challenges",
    title: "Lagos 50KM Running Challenge",
    emoji: "🏃",
    area: "victoria-island",
    distanceKm: 0,
    meta: "Goal: 50km this month · 11 days left",
    verified: true,
    href: "/app/progress",
  },
];

// ---------- Feed (PRD §19) ----------

export const POSTS: Post[] = [
  {
    id: "p-1",
    authorId: "david",
    authorName: "David",
    authorTone: 0,
    kind: "workout",
    text: "David completed a 5KM run in 29:42.",
    ago: "2h",
    likes: 23,
    liked: true,
    comments: [
      { id: "c-1", authorName: "Segun Adebayo", text: "That's a 5:56/km. Solid.", ago: "1h" },
      { id: "c-2", authorName: "Tunde Bakare", text: "See you Saturday for the long one 👊", ago: "48m" },
      { id: "c-3", authorName: "Bola Adeyemi", text: "Congrats on the pace!", ago: "31m" },
      { id: "c-4", authorName: "Amaka Uche", text: "This is the push I needed today.", ago: "12m" },
    ],
    stats: [
      { label: "Distance", value: "5.00 km" },
      { label: "Time", value: "29:42" },
      { label: "Pace", value: "5:56/km" },
    ],
    accent: "run",
  },
  {
    id: "p-2",
    authorId: "ngozi",
    authorName: "Ngozi Eze",
    authorTone: 1,
    communityId: "lekki-strength-crew",
    kind: "achievement",
    text: "Squat went 80kg → 95kg for a clean triple. Eleven months of showing up.",
    ago: "5h",
    likes: 61,
    liked: false,
    comments: [
      { id: "c-5", authorName: "Tobi Alabi", text: "Absolute machine.", ago: "4h" },
      { id: "c-6", authorName: "David", text: "Form looks dialed in 🔥", ago: "3h" },
    ],
    stats: [
      { label: "Squat", value: "95 kg" },
      { label: "Set", value: "3 × 3" },
    ],
    accent: "pr",
  },
  {
    id: "p-3",
    authorId: "tunde",
    authorName: "Tunde Bakare",
    authorTone: 2,
    communityId: "lagos-runners",
    kind: "photo",
    text: "5AM crew. The bridge was empty and the water was flat. This is why we wake up before the traffic.",
    ago: "8h",
    likes: 47,
    liked: false,
    comments: [
      { id: "c-7", authorName: "Segun Adebayo", text: "Best loop in the city.", ago: "7h" },
      { id: "c-8", authorName: "Chidinma Okafor", text: "Adding this to my Saturday list.", ago: "6h" },
    ],
    stats: [
      { label: "Distance", value: "8.2 km" },
      { label: "Time", value: "44:10" },
    ],
    accent: "photo",
  },
  {
    id: "p-4",
    authorId: "chidinma",
    authorName: "Chidinma Okafor",
    authorTone: 3,
    communityId: "yaba-run-club",
    kind: "milestone",
    text: "30-day streak. I did not believe this sentence when I started.",
    ago: "1d",
    likes: 118,
    liked: true,
    comments: [
      { id: "c-9", authorName: "Amaka Uche", text: "Month one done. On to month two.", ago: "1d" },
      { id: "c-10", authorName: "Funke Balogun", text: "Incredible. Proud of you 👏", ago: "22h" },
    ],
    stats: [{ label: "Streak", value: "30 days" }],
    accent: "streak",
  },
  {
    id: "p-5",
    authorId: "emeka",
    authorName: "Emeka Nwosu",
    authorTone: 4,
    kind: "workout",
    text: "Bench press 45kg → 55kg this month. Small plate, big difference.",
    ago: "1d",
    likes: 34,
    liked: false,
    comments: [{ id: "c-11", authorName: "Tobi Alabi", text: "60 is already in range.", ago: "1d" }],
    stats: [
      { label: "Bench", value: "55 kg" },
      { label: "Set", value: "4 × 6" },
    ],
    accent: "pr",
  },
  {
    id: "p-6",
    authorId: "funke",
    authorName: "Funke Balogun",
    authorTone: 7,
    communityId: "surulere-yoga-circle",
    kind: "text",
    text: "Reminder that resting is part of the programme. Took two days off after three weeks without a break and my shoulders finally stopped talking back.",
    ago: "2d",
    likes: 89,
    liked: false,
    comments: [
      { id: "c-12", authorName: "Bola Adeyemi", text: "Recovery is training.", ago: "2d" },
    ],
    stats: [],
    accent: "recovery",
  },
];

// ---------- Workouts (PRD §15) ----------

export const WORKOUTS: Workout[] = [
  {
    id: "w-1",
    userId: "david",
    activity: "running",
    dayLabel: "Today",
    date: "Wed 29 Oct",
    time: "7:10 AM",
    durationMin: 30,
    calories: 312,
    location: "Lekki Phase 1",
    sharedToFeed: true,
    isPR: true,
    prNote: "Fastest 5K",
    run: { distanceKm: 5, pacePerKm: "5:56" },
    summary: "5.00 km · 29:42 · 5:56/km",
  },
  {
    id: "w-2",
    userId: "david",
    activity: "gym",
    dayLabel: "Monday",
    date: "Mon 27 Oct",
    time: "6:20 PM",
    durationMin: 68,
    calories: 420,
    location: "i-Fitness Lekki",
    sessionId: "bench-squat-night",
    sharedToFeed: true,
    isPR: true,
    prNote: "Bench press 55kg",
    strength: [
      { exercise: "Bench Press", sets: 4, reps: 6, weightKg: 55 },
      { exercise: "Back Squat", sets: 4, reps: 8, weightKg: 80 },
      { exercise: "Barbell Row", sets: 3, reps: 10, weightKg: 50 },
    ],
    summary: "3 exercises · 420 kcal · 1h 08m",
  },
  {
    id: "w-3",
    userId: "david",
    activity: "running",
    dayLabel: "Sunday",
    date: "Sun 26 Oct",
    time: "7:30 AM",
    durationMin: 52,
    calories: 540,
    location: "Eko Atlantic",
    sharedToFeed: false,
    isPR: false,
    run: { distanceKm: 8.2, pacePerKm: "6:20" },
    summary: "8.20 km · 52:00 · 6:20/km",
  },
  {
    id: "w-4",
    userId: "david",
    activity: "gym",
    dayLabel: "Saturday",
    date: "Sat 25 Oct",
    time: "8:05 AM",
    durationMin: 75,
    calories: 480,
    location: "i-Fitness Lekki",
    sharedToFeed: true,
    isPR: false,
    strength: [
      { exercise: "Deadlift", sets: 4, reps: 5, weightKg: 100 },
      { exercise: "Overhead Press", sets: 4, reps: 8, weightKg: 35 },
    ],
    summary: "2 exercises · 480 kcal · 1h 15m",
  },
  {
    id: "w-5",
    userId: "david",
    activity: "gym",
    dayLabel: "Thursday",
    date: "Thu 23 Oct",
    time: "6:40 PM",
    durationMin: 61,
    calories: 395,
    location: "i-Fitness Lekki",
    sharedToFeed: false,
    isPR: false,
    strength: [
      { exercise: "Bench Press", sets: 4, reps: 6, weightKg: 52.5 },
      { exercise: "Lat Pulldown", sets: 3, reps: 12, weightKg: 55 },
    ],
    summary: "2 exercises · 395 kcal · 1h 01m",
  },
  {
    id: "w-6",
    userId: "david",
    activity: "running",
    dayLabel: "Tuesday",
    date: "Tue 21 Oct",
    time: "6:05 AM",
    durationMin: 38,
    calories: 390,
    location: "Lekki Phase 1",
    sharedToFeed: true,
    isPR: false,
    run: { distanceKm: 6, pacePerKm: "6:20" },
    summary: "6.00 km · 38:00 · 6:20/km",
  },
];

// ---------- Progress (PRD §16) ----------

function buildHeatmap(): ProgressSnapshot["heatmap"] {
  // Deterministic pattern so the heatmap is stable across renders.
  const rows: ProgressSnapshot["heatmap"] = [];
  const pattern = [0, 2, 0, 3, 1, 0, 2, 3, 0, 1, 2, 0, 3, 2];
  for (let i = 89; i >= 0; i--) {
    const d = new Date();
    d.setDate(d.getDate() - i);
    const seed = pattern[(i * 5 + d.getDate()) % pattern.length]!;
    // Rest the last two days except today — keeps the narrative honest.
    const intensity = (i === 1 || i === 2) && seed > 0 ? 0 : seed;
    rows.push({
      date: d.toISOString().slice(0, 10),
      intensity: intensity as 0 | 1 | 2 | 3,
      label: `${d.getDate()} ${["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"][d.getMonth()]}`,
    });
  }
  return rows;
}

export const PROGRESS: ProgressSnapshot = {
  days: 90,
  workouts: 47,
  trainingHours: 18,
  personalRecords: 12,
  weeklyAverage: 3.6,
  streak: 7,
  weeklyTarget: 4,
  weeklyCompleted: 3,
  weeklyTrend: [3, 4, 3, 4, 4, 3, 4, 3, 4, 4, 3, 3],
  distanceTrend: [14, 18, 16, 22, 19, 15, 24, 21, 17, 25, 20, 18],
  byActivity: [
    { activity: "gym", count: 24, pct: 51 },
    { activity: "running", count: 17, pct: 36 },
    { activity: "yoga", count: 4, pct: 9 },
    { activity: "swimming", count: 2, pct: 4 },
  ],
  heatmap: buildHeatmap(),
  records: [
    { id: "r-1", exercise: "Bench Press", from: "45", to: "55", unit: "kg", ago: "2h ago", isNew: true },
    { id: "r-2", exercise: "5K Run", from: "31:10", to: "29:42", unit: "", ago: "2h ago", isNew: true },
    { id: "r-3", exercise: "Back Squat", from: "75", to: "80", unit: "kg", ago: "4d ago", isNew: false },
    { id: "r-4", exercise: "Deadlift", from: "95", to: "100", unit: "kg", ago: "1w ago", isNew: false },
    { id: "r-5", exercise: "Overhead Press", from: "30", to: "35", unit: "kg", ago: "2w ago", isNew: false },
  ],
};

// ---------- Challenges (PRD §18) ----------

export const CHALLENGES: Challenge[] = [
  {
    id: "ch-gym-30",
    title: "30-Day Gym Challenge",
    emoji: "🏋️",
    communityId: "lekki-strength-crew",
    hostName: "Ngozi Eze",
    goal: "20 workouts",
    metric: "workouts",
    target: 20,
    unit: "workouts",
    participants: 428,
    endsIn: "11 days left",
    joined: true,
    you: { rank: 41, value: 14, pct: 70 },
    leaderboard: [
      { rank: 1, name: "Ngozi Eze", tone: 1, value: 19, you: false },
      { rank: 2, name: "Tobi Alabi", tone: 4, value: 18, you: false },
      { rank: 3, name: "Emeka Nwosu", tone: 4, value: 17, you: false },
      { rank: 41, name: "You", tone: 0, value: 14, you: true },
      { rank: 42, name: "Zainab Ibrahim", tone: 3, value: 13, you: false },
      { rank: 43, name: "Amaka Uche", tone: 2, value: 12, you: false },
    ],
  },
  {
    id: "ch-50km",
    title: "Lagos 50KM Running Challenge",
    emoji: "🏃",
    communityId: "lagos-runners",
    hostName: "Segun Adebayo",
    goal: "Run 50km this month",
    metric: "distance",
    target: 50,
    unit: "km",
    participants: 891,
    endsIn: "11 days left",
    joined: true,
    you: { rank: 312, value: 34.4, pct: 69 },
    leaderboard: [
      { rank: 1, name: "Segun Adebayo", tone: 1, value: 112.5, you: false },
      { rank: 2, name: "Tunde Bakare", tone: 2, value: 98.2, you: false },
      { rank: 3, name: "Bola Adeyemi", tone: 5, value: 84.7, you: false },
      { rank: 312, name: "You", tone: 0, value: 34.4, you: true },
    ],
  },
  {
    id: "ch-consistency-30",
    title: "30-Day Consistency Challenge",
    emoji: "🔥",
    hostName: "Lagos Runners",
    goal: "Exercise 4× per week",
    metric: "streak",
    target: 4,
    unit: "days/week",
    participants: 1204,
    endsIn: "11 days left",
    joined: false,
    you: { rank: 0, value: 0, pct: 0 },
    leaderboard: [
      { rank: 1, name: "Chidinma Okafor", tone: 3, value: 30, you: false },
      { rank: 2, name: "Funke Balogun", tone: 7, value: 28, you: false },
      { rank: 3, name: "Amaka Uche", tone: 2, value: 27, you: false },
    ],
  },
];

// ---------- Trainers (PRD §11 discovery; §21 profiles are Phase 2) ----------

export const TRAINERS: Trainer[] = [
  {
    id: "t-ify",
    name: "Ify Okonkwo",
    initials: "IO",
    tone: 1,
    profession: "Personal Trainer",
    speciality: "Strength & hypertrophy",
    area: "lekki",
    rating: 4.9,
    reviewCount: 127,
    fromPrice: "₦15,000 / session",
    availability: "Mon – Sat, 6 AM – 8 PM",
    verified: true,
  },
  {
    id: "t-sam",
    name: "Sam Adeleke",
    initials: "SA",
    tone: 2,
    profession: "Running Coach",
    speciality: "Marathon & half-marathon",
    area: "victoria-island",
    rating: 4.8,
    reviewCount: 84,
    fromPrice: "₦12,000 / session",
    availability: "Tue, Thu, Sat mornings",
    verified: true,
  },
  {
    id: "t-titi",
    name: "Titi Balogun",
    initials: "TB",
    tone: 5,
    profession: "Nutritionist",
    speciality: "Body composition",
    area: "ikeja",
    rating: 4.7,
    reviewCount: 63,
    fromPrice: "₦10,000 / consultation",
    availability: "Weekdays, by appointment",
    verified: false,
  },
  {
    id: "t-uche",
    name: "Dr. Uche Nnadi",
    initials: "UN",
    tone: 4,
    profession: "Physiotherapist",
    speciality: "Injury rehab",
    area: "victoria-island",
    rating: 4.9,
    reviewCount: 201,
    fromPrice: "₦20,000 / session",
    availability: "Mon – Fri, 9 AM – 5 PM",
    verified: true,
  },
  {
    id: "t-kola",
    name: "Kola Mensah",
    initials: "KM",
    tone: 6,
    profession: "Strength Coach",
    speciality: "Powerlifting",
    area: "lekki",
    rating: 4.6,
    reviewCount: 45,
    fromPrice: "₦14,000 / session",
    availability: "Evenings & weekends",
    verified: false,
  },
  {
    id: "t-amara",
    name: "Amara Eze",
    initials: "AE",
    tone: 7,
    profession: "Yoga Instructor",
    speciality: "Mobility & recovery",
    area: "surulere",
    rating: 4.8,
    reviewCount: 72,
    fromPrice: "₦9,000 / class",
    availability: "Mon, Thu, Sun mornings",
    verified: true,
  },
];

// ---------- Notifications (PRD §20) ----------

export const NOTIFICATIONS: AppNotification[] = [
  {
    id: "n-1",
    kind: "accountability",
    text: "Your weekly goal is almost complete",
    sub: "3 of 4 workouts done — one more session closes the week.",
    ago: "20m",
    read: false,
    href: "/app/progress",
  },
  {
    id: "n-2",
    kind: "event",
    text: "Bench & Squat Night starts at 6:00 PM",
    sub: "i-Fitness Lekki · 12 of 40 spots taken",
    ago: "1h",
    read: false,
    href: "/app/sessions/bench-squat-night",
  },
  {
    id: "n-3",
    kind: "social",
    text: "Segun Adebayo commented on your run",
    sub: "\"That's a 5:56/km. Solid.\"",
    ago: "1h",
    read: false,
    href: "/app",
  },
  {
    id: "n-4",
    kind: "fitness",
    text: "New personal record — Bench Press",
    sub: "45kg → 55kg",
    ago: "2h",
    read: true,
    href: "/app/progress",
  },
  {
    id: "n-5",
    kind: "social",
    text: "Ngozi Eze posted in Lekki Strength Crew",
    sub: "Squat went 80kg → 95kg for a clean triple.",
    ago: "5h",
    read: true,
    href: "/app/community/lekki-strength-crew",
  },
  {
    id: "n-6",
    kind: "event",
    text: "Saturday 5KM Run — 47 of 100 spots taken",
    sub: "Lekki Phase 1 · 6:00 AM",
    ago: "8h",
    read: true,
    href: "/app/sessions/sat-5km",
  },
  {
    id: "n-7",
    kind: "fitness",
    text: "7-day streak kept 🔥",
    sub: "You have trained every day this week.",
    ago: "1d",
    read: true,
    href: "/app/progress",
  },
  {
    id: "n-8",
    kind: "social",
    text: "3 people joined Lagos Runners today",
    ago: "1d",
    read: true,
    href: "/app/community",
  },
];
